# -*- coding: utf-8 -*-
"""QR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxjj6kvR4tCLOZFfW41jRiSTa1R-c19B
"""

pip install qrcode

import qrcode
from PIL import Image

# Define the website. If possible, use a shortened link.
data = "https://www.instagram.com/pfaecreasenverde/"

# Creare QR code
qr = qrcode.QRCode(
    version=1, # Size between 1 to 40. However, I do not recommend you change this parameter. Otherwise it will be
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=4,
)

# Add data to the QR

qr.add_data(data)
qr.make(fit=True)

# Create the QR image

img = qr.make_image(fill_color="black", back_color="white").convert("RGBA")

# Make the back color turn transparent

datas = img.getdata()
new_data = []
for item in datas:
    if item [:3] == (255, 255, 255):
      new_data.append((255, 255, 255, 0))
    else:
      new_data.append(item)

img.putdata(new_data)

# Save QR

img.save("qr_code.png")

print("QR created")